### ISSUE TITLE
Error Cannot find module '@babel/runtime/helpers/defineProperty'

### ISSUE THREAD

**Issue by theodorfoerster** [fabulator/gpx-builder#34]
Hi, When following your readme, I get the following error:
```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@babel/runtime/helpers/defineProperty'
```

I have the impression, that the dependencies are not properly defined. 

Please advice! 🙏

**Comment by fabulator** [comment]
@theodorfoerster sorry about that, it was fixed in 2.2.1. Or you can use ```npm install @babel/runtime```
